(ns shipyard.fixtures
  "Generated meshes for tests.

  Everything is produced in memory as a byte[]: unit tests must not touch disk
  (TECHNICAL.md §10.1), and generated solids beat committed binaries because the
  expected triangle count and bbox fall out of the generator rather than being
  recorded from a run."
  (:import [java.nio ByteBuffer ByteOrder]))

(defn cube
  "Axis-aligned cube of side `s` centred on the origin. 12 triangles, 8 distinct
  positions, every edge a hard 90-degree crease."
  ([] (cube 2.0))
  ([s]
   (let [h (/ (double s) 2.0)
         v (fn [a b c] [(* a h) (* b h) (* c h)])
         ;; six faces, two triangles each, consistent outward winding
         quad (fn [a b c d] [[a b c] [a c d]])]
     (vec (mapcat (partial apply quad)
                  [[(v -1 -1  1) (v  1 -1  1) (v  1  1  1) (v -1  1  1)]   ; +z
                   [(v  1 -1 -1) (v -1 -1 -1) (v -1  1 -1) (v  1  1 -1)]   ; -z
                   [(v -1 -1 -1) (v -1 -1  1) (v -1  1  1) (v -1  1 -1)]   ; -x
                   [(v  1 -1  1) (v  1 -1 -1) (v  1  1 -1) (v  1  1  1)]   ; +x
                   [(v -1  1  1) (v  1  1  1) (v  1  1 -1) (v -1  1 -1)]   ; +y
                   [(v -1 -1 -1) (v  1 -1 -1) (v  1 -1  1) (v -1 -1  1)]]))))) ; -y

(defn uv-sphere
  "Sphere of radius `r` with `rings` latitude bands and `segments` longitude
  steps. Poles emit one triangle per segment, everything between emits two, so
  the triangle count is exactly 2*segments*(rings-1) with no degenerates.

  Smooth and closed, which is what makes it the counterpart to the cube: it
  should weld to V/T near 0.5 and be untouched by crease splitting."
  [r rings segments]
  (let [p (fn [i j]
            (let [lat (* Math/PI (/ (double i) rings))
                  lon (* 2.0 Math/PI (/ (double (mod j segments)) segments))]
              [(* r (Math/sin lat) (Math/cos lon))
               (* r (Math/cos lat))
               (* r (Math/sin lat) (Math/sin lon))]))]
    (vec (for [i (range rings)
               j (range segments)
               t (cond
                   ;; Pole fans wind opposite to each other: going the same way
                   ;; round the ring puts the top cap's normal inward. Verified
                   ;; by asserting every face normal points away from the centre.
                   (zero? i)          [[(p 0 0) (p 1 (inc j)) (p 1 j)]]
                   (= i (dec rings))  [[(p i j) (p i (inc j)) (p rings 0)]]
                   :else              [[(p i j) (p i (inc j)) (p (inc i) (inc j))]
                                       [(p i j) (p (inc i) (inc j)) (p (inc i) j)]])]
           t))))

(defn mount-plate
  "A single rectangular authoring face, triangulated the same way the M2
  contract examples are. The center ray in the E2E viewport hits this facet
  deterministically."
  []
  [[[0.0 0.0 0.0] [4.0 0.0 0.0] [0.0 2.0 0.0]]
   [[4.0 0.0 0.0] [4.0 2.0 0.0] [0.0 2.0 0.0]]])

(defn triangle-count [tris] (count tris))

(defn bbox [tris]
  (let [pts (mapcat identity tris)]
    {:min (mapv (fn [k] (apply min (map #(nth % k) pts))) [0 1 2])
     :max (mapv (fn [k] (apply max (map #(nth % k) pts))) [0 1 2])}))

(defn ->binary-stl
  "Encode triangles as a binary STL. `header` lets a test plant the classic trap
  of a binary file whose header text begins with \"solid\"."
  (^bytes [tris] (->binary-stl tris "generated by shipyard tests"))
  (^bytes [tris header]
   (let [n   (count tris)
         buf (doto (ByteBuffer/allocate (+ 84 (* 50 n))) (.order ByteOrder/LITTLE_ENDIAN))
         hb  (.getBytes ^String header "US-ASCII")]
     (.put buf (byte-array 80))
     (.position buf 0)
     (.put buf hb 0 (min 80 (alength hb)))
     (.position buf 80)
     (.putInt buf n)
     (doseq [t tris]
       ;; Stored normal left at zero on purpose: real files often do this, and
       ;; the parser must not depend on it (shipyard.mesh.stl docstring).
       (dotimes [_ 3] (.putFloat buf 0.0))
       (doseq [v t, c v] (.putFloat buf (float c)))
       (.putShort buf 0))
     (.array buf))))

(defn ->ascii-stl
  "Encode triangles as an ASCII STL. `line-ending` defaults to \\n; pass \\r\\n
  to reproduce the CRLF file that exists in the real library."
  (^bytes [tris] (->ascii-stl tris "\n"))
  (^bytes [tris line-ending]
   (let [sb (StringBuilder.)
         nl (fn [s] (.append sb ^String s) (.append sb ^String line-ending))]
     (nl "solid generated")
     (doseq [t tris]
       (nl "  facet normal 0.0 0.0 0.0")
       (nl "    outer loop")
       (doseq [[x y z] t] (nl (format "      vertex %.6f %.6f %.6f" (double x) (double y) (double z))))
       (nl "    endloop")
       (nl "  endfacet"))
     (nl "endsolid generated")
     (.getBytes (str sb) "US-ASCII"))))
