(ns shipyard.e2e.help-test
  (:require [clojure.string :as str]
            [clojure.test :refer [deftest is]]
            [shipyard.assembly-fixture :as fixture]
            [shipyard.e2e.named-ship-test :as named]
            [shipyard.e2e.support :as s]
            [shipyard.loadout-fixture :as lf]
            [shipyard.loadout.db :as classes])
  (:import [com.microsoft.playwright Page]))

(defn- help! [driver selector expected]
  (let [^Page page (:page driver)]
    (s/js driver "() => document.activeElement.blur()")
    (.focus page selector)
    (s/wait-visible! driver "[role=tooltip]")
    (is (str/includes? (s/text driver "[role=tooltip]") expected))
    (is (s/js driver "() => document.activeElement.getAttribute('aria-describedby').split(' ').includes('control-tooltip')")
        "Focused controls reference the shared tooltip")
    (is (s/js driver "() => {const r=document.querySelector('[role=tooltip]').getBoundingClientRect();return r.left>=0&&r.top>=0&&r.right<=innerWidth&&r.bottom<=innerHeight}")
        "Help fits the viewport even inside a scrolling inspector")
    (.press (.keyboard page) "Escape")
    (is (s/js driver "() => document.querySelector('[role=tooltip]').hidden"))
    (is (not (s/js driver "() => (document.activeElement.getAttribute('aria-describedby')||'').includes('control-tooltip')"))
        "Dismissal removes the temporary description reference")))

(deftest shared-help-follows-controls-through-workspace-and-inspector-swaps
  (s/assert-bundle!)
  (let [started (fixture/start! true) sys (:system started) driver (s/make-driver)
        ^Page page (:page driver)]
    (try
      (classes/put! (:shipyard.loadout/db sys)
                    {:loadout/id (random-uuid) :loadout/name "Help Cruiser"
                     :loadout/hull (:hull lf/draft) :loadout/slots lf/assignments} :create)
      (s/go! driver (s/base-url sys))
      (s/wait-visible! driver "#bulk-orient-filters select[name=variant]")
      (.hover page "#bulk-orient-filters select[name=variant]")
      (s/wait-visible! driver "[role=tooltip]")
      (is (str/includes? (s/text driver "[role=tooltip]") "supported-only"))
      (let [{:keys [x y width height]} (s/bounds driver "[role=tooltip]")]
        (.move (.mouse page) (+ x (/ width 2)) (+ y (/ height 2))))
      (is (s/js driver "() => !document.querySelector('[role=tooltip]').hidden")
          "Pointer users can move onto the help without dismissing it")
      (.press (.keyboard page) "Escape")
      (is (s/js driver "() => document.querySelector('[role=tooltip]').hidden"))
      (s/click! driver (str "[data-part-row='" (:prow fixture/ids) "'] > summary"))
      (s/wait-visible! driver ".part-row-edit")
      (help! driver ".part-row-edit__actions button" "orientation angles")
      (help! driver "[data-row-orientation-reset]" "source orientation")
      (s/click! driver (str "[data-part-row='" (:prow fixture/ids) "'] > summary"))
      (s/open-part! driver "prow")
      (s/await-part driver (:prow fixture/ids))
      (s/click! driver "[data-detail-tab=regions]")
      (s/wait-visible! driver "#part-regions")
      (help! driver "button[aria-label='Region brush help']" "Release to save regions")
      (help! driver "[data-region-mode=facets]" "individual triangles")
      (help! driver "[data-region-mode=faces]" "connected surfaces")
      (s/click! driver "[data-region-mode=faces]")
      (help! driver "#region-angle" "Maximum angle")
      (help! driver "#region-stroke input[name=mirror]" "hidden faces")
      (s/check! driver "#region-stroke input[name=mirror]")
      (help! driver "#region-stroke select[name=mirror-axis]" "part’s axes")
      (help! driver "#region-stroke input[name=mirror-offset]" "Leave blank")
      (help! driver "#region-fill button" "Primary clears")
      (.setViewportSize page 600 900)
      (help! driver "button[aria-label='Region brush help']" "Alt+drag")
      (.setViewportSize page 1280 900)
      (s/click! driver "[data-workspace-mode=settings]")
      (s/wait-visible! driver "#settings-workspace")
      (help! driver "#cut-defaults button" "Existing cuts keep")
      (help! driver "button[aria-label='Universal class help']" "every hull class")
      (help! driver ".settings-workspace__rename button" "all libraries")
      (is (not (str/includes? (s/text driver "#settings-workspace") "Classification values are shared")))
      ;; A hovered tooltip must disappear when HTMX removes its originating control.
      (.hover page "#cut-defaults button")
      (s/wait-visible! driver "[role=tooltip]")
      (s/click! driver "[data-workspace-mode=ships]")
      (s/wait-visible! driver "#library[data-ship-view=table]")
      (is (s/js driver "() => document.querySelector('[role=tooltip]').hidden"))
      (s/open-class! driver "Help Cruiser")
      (s/wait-visible! driver ".assembly__save")
      (help! driver "input[name=allow-other-factions]" "without relaxing class matching")
      (named/tab! driver "Schemes")
      (s/fill-and-blur! driver "#scheme-create input[name=name]" "Help Fleet")
      (s/click! driver "#scheme-create button")
      (s/wait-visible! driver "#scheme-material")
      (help! driver "#scheme-material button" "every named ship")
      (named/tab! driver "Customize")
      (s/select-option! driver "#paint-create select[name=scheme]" "Help Fleet")
      (named/create! driver "Help Vessel")
      (help! driver "#paint-scheme select" "preserving its custom paint")
      (help! driver "button[aria-label='Detail brush help']" "occluded surfaces")
      (help! driver "#paint-brush button[value=undo]" "20 strokes")
      (help! driver "#paint-brush button[value=redo]" "20 strokes")
      (help! driver "#mount-colors-toggle" "enable custom painting")
      (is (not (str/includes? (s/text driver "#detail") "Whole visible triangles, nearest surface only")))
      (is (zero? (s/count-els driver ".masthead__stats")))
      (s/screenshot-el! driver "#detail" (java.io.File. "/tmp/shipyard-ui-copy-customize.png"))
      (finally (s/quit! driver) (fixture/stop! started)))))
