(ns shipyard.e2e.ship-table-test
  (:require [clojure.test :refer [deftest is]]
            [shipyard.assembly-fixture :as fixture]
            [shipyard.loadout-fixture :as lf]
            [shipyard.loadout.db :as classes]
            [shipyard.ship.db :as ships]
            [shipyard.e2e.support :as s])
  (:import [com.microsoft.playwright Page]))

(deftest resume-assembly-requires-a-retained-hull
  (s/assert-bundle!)
  (let [started (fixture/start! true) sys (:system started) driver (s/make-driver)
        state (:state (:shipyard.assembly/db sys))
        disabled? #(s/js driver "() => document.querySelector('[data-ship-new]').disabled")]
    (try
      (classes/put! (:shipyard.loadout/db sys)
                    {:loadout/id (random-uuid) :loadout/name "Saved cruiser"
                     :loadout/hull (:hull fixture/ids) :loadout/slots {}} :create)
      (s/go! driver (s/base-url sys))
      (s/ship-table! driver)
      (is (disabled?) "Saved classes do not create an in-progress assembly")
      (s/click! driver ".ship-table__new button")
      (s/wait-visible! driver ".assembly__hull")
      (s/click! driver "[data-ship-back]")
      (s/wait-visible! driver "#ship-filters")
      (is (disabled?) "A new empty draft cannot be resumed")
      (is (pos? (get-in @state [:draft :revision])))
      (s/click! driver ".ship-table__new button")
      (s/wait-visible! driver ".assembly__hull")
      (s/select-option! driver ".assembly__hull select[name=part-id]" "hull")
      (s/click! driver ".assembly__hull button")
      (s/await-assembly-prepared! driver 1)
      (s/fill-and-blur! driver ".assembly__save input[name=name]" "Working cruiser")
      (s/click! driver "[data-ship-back]")
      (s/wait-visible! driver "#ship-filters")
      (let [draft (:draft @state)]
        (is (not (disabled?)) "An unsaved hull-only assembly can be resumed")
        (s/click! driver "[data-workspace-mode=browse]")
        (s/wait-visible! driver "#bulk-orient-results .bulk-orient__row")
        (s/ship-table! driver)
        (is (not (disabled?)) "Workspace navigation retains the assembly")
        (s/click! driver "[data-ship-new]")
        (s/await-assembly-prepared! driver 1)
        (is (= draft (:draft @state)))
        (is (= "Working cruiser" (s/js driver "() => document.querySelector('.assembly__save input[name=name]').value")))
        (is (= (:hull fixture/ids) (get-in @state [:draft :hull])))
        (s/click! driver "[data-ship-back]")
        (s/wait-visible! driver "#ship-filters")
        (s/click! driver ".ship-table__new button")
        (s/wait-visible! driver ".assembly-discard")
        (s/click! driver ".assembly-discard button:text-is('Discard and create class')")
        (s/wait-visible! driver ".assembly__hull")
        (is (s/wait-until #(empty? (:parts (s/stats driver)))))
        (s/click! driver "[data-ship-back]")
        (s/wait-visible! driver "#ship-filters")
        (is (disabled?) "Discarding the assembly disables Resume again")
        (is (nil? (get-in @state [:draft :hull]))))
      (finally (s/quit! driver) (fixture/stop! started)))))

(deftest table-editor-and-named-ship-round-trip
  (let [started (fixture/start! true) sys (:system started) driver (s/make-driver)
        class-db (:shipyard.loadout/db sys) ship-db (:shipyard.ship/db sys)
        class {:loadout/id (random-uuid) :loadout/name "Cruiser" :loadout/hull (:hull lf/draft) :loadout/slots lf/assignments}]
    (try
      (classes/put! class-db class :create)
      (s/go! driver (s/base-url sys))
      (s/ship-table! driver)
      (is (= ["Part Browser" "Ship Browser" "Settings"] (s/js driver "() => [...document.querySelectorAll('.masthead__mode')].map(e=>e.textContent)")))
      (is (> (s/width driver "#library") 1000))
      (s/fill! driver "#ship-filters input[name=q]" "Cruiser")
      (is (s/wait-until #(= 1 (s/count-els driver ".ship-card"))))
      (.dblclick ^Page (:page driver) ".ship-table__row[aria-label='Open class Cruiser']")
      (s/wait-visible! driver ".assembly__save")
      (is (s/wait-until #(= 13 (count (get-in (s/stats driver) [:assembly :slots])))))
      (is (= ["Assembly" "Schemes" "Customize"] (s/js driver "() => [...document.querySelectorAll('.ship-inspector nav button')].map(e=>e.textContent)")))
      (is (false? (s/js driver "() => document.querySelector('#library').checkVisibility()")))
      (s/click! driver ".ship-inspector nav button:text-is('Schemes')")
      (s/wait-visible! driver "#scheme-create")
      (s/fill-and-blur! driver "#scheme-create input[name=name]" "Fleet")
      (s/click! driver "#scheme-create button")
      (s/wait-visible! driver "#scheme-material")
      (s/click! driver ".ship-inspector nav button:text-is('Customize')")
      (s/wait-visible! driver "#paint-create")
      (s/fill-and-blur! driver "#paint-create input[name=name]" "Resolute")
      (s/click! driver "#paint-create button")
      (s/wait-visible! driver "#paint-brush")
      (is (= 1 (count (:ships (ships/snapshot! ship-db)))))
      (let [id (-> (ships/snapshot! ship-db) :ships keys first)]
        (s/click! driver "[data-ship-back]")
        (s/wait-visible! driver "#ship-filters")
        (is (= "Cruiser" (s/js driver "() => document.querySelector('#ship-filters input[name=q]').value")))
        (s/click! driver ".ship-card__ships summary")
        (s/wait-visible! driver (str "[data-ship-id='" id "']"))
        (.dblclick ^Page (:page driver) (str "[data-ship-id='" id "'] .ship-table__name"))
        (s/wait-visible! driver "#paint-brush")
        (is (= "Customize" (s/text driver ".ship-inspector nav button[aria-current=page]")))
        (s/click! driver ".ship-inspector nav button:text-is('Assembly')")
        (s/wait-visible! driver ".assembly__save")
        (s/fill-and-blur! driver ".assembly__save input[name=name]" "Cruiser refit")
        (s/click! driver "[data-ship-back]")
        (s/wait-visible! driver "#ship-filters")
        (is (true? (s/js driver "() => document.querySelector('.ship-card__ships').open")))
        (s/click! driver "[data-ship-new]")
        (s/wait-visible! driver ".assembly__save")
        (is (= "Cruiser refit" (s/js driver "() => document.querySelector('.assembly__save input[name=name]').value")))
        (s/click! driver ".assembly__save button")
        (is (s/wait-until #(= "Cruiser refit" (get-in (classes/snapshot! class-db) [:loadouts (:loadout/id class) :loadout/name]))))
        (s/click! driver ".ship-inspector nav button:text-is('Customize')")
        (s/wait-visible! driver "#paint-brush")
        (is (= id (get-in @(:state (:shipyard.paint/db sys)) [:draft :ship-id])))
        (s/screenshot-el! driver ".layout" (java.io.File. "/tmp/shipyard-ship-editor.png"))
        (s/click! driver "[data-ship-back]")
        (s/wait-visible! driver "#ship-filters")
        (s/screenshot-el! driver ".layout" (java.io.File. "/tmp/shipyard-ship-table.png"))
        (s/click! driver ".ship-table__new button")
        (s/wait-visible! driver ".assembly__hull")
        (is (s/wait-until #(empty? (:parts (s/stats driver)))))
        (is (zero? (s/count-els driver ".assembly__save"))))
      (finally (s/quit! driver) (fixture/stop! started)))))

(deftest table-scroll-and-new-class-without-viewport
  (let [started (fixture/start! true) sys (:system started) driver (s/make-driver)
        class-db (:shipyard.loadout/db sys) ^Page page (:page driver)]
    (try
      (.route page "**/js/viewport.js"
              (reify java.util.function.Consumer
                (accept [_ route] (.abort ^com.microsoft.playwright.Route route))))
      (doseq [n (range 25)]
        (classes/put! class-db {:loadout/id (random-uuid) :loadout/name (format "Class %02d" n)
                                :loadout/hull (:hull lf/draft) :loadout/slots {}} :create))
      (s/go! driver (s/base-url sys))
      (s/ship-table! driver)
      (.scrollIntoViewIfNeeded (.locator page ".ship-table__row[aria-label='Open class Class 24']"))
      (let [scroll (s/js driver "() => document.getElementById('ship-results').scrollTop")]
        (is (pos? scroll))
        (.press (.locator page ".ship-table__row[aria-label='Open class Class 24']") "Enter")
        (s/wait-visible! driver ".assembly__save")
        (is (= (str scroll) (get-in @(:state (:shipyard.workspace/db sys)) [:workspaces :ships :filters "table-scroll"])))
        (s/click! driver "[data-ship-back]")
        (s/wait-visible! driver "#ship-filters")
        (is (s/wait-until #(= scroll (s/js driver "() => document.getElementById('ship-results').scrollTop")))
            (str {:expected scroll :actual (s/js driver "() => document.getElementById('ship-results').scrollTop")
                  :filters (get-in @(:state (:shipyard.workspace/db sys)) [:workspaces :ships :filters])})))
      (s/click! driver ".ship-table__new button")
      (s/wait-visible! driver ".assembly__hull")
      (is (zero? (s/count-els driver ".assembly__save")))
      (s/select-option! driver ".assembly__hull select[name=part-id]" "hull")
      (s/click! driver ".assembly__hull button")
      (s/wait-visible! driver ".assembly__save")
      (s/fill-and-blur! driver ".assembly__save input[name=name]" "Working copy")
      (s/click! driver ".ship-inspector nav button:text-is('Customize')")
      (s/wait-visible! driver "#detail [role=alert]")
      (is (zero? (s/count-els driver "#paint-create")))
      (s/click! driver "[data-ship-back]")
      (s/wait-visible! driver "#ship-filters")
      (s/click! driver ".ship-table__new button")
      (s/wait-visible! driver ".assembly-discard")
      (s/click! driver ".assembly-discard button:text-is('Cancel')")
      (s/wait-visible! driver "#ship-filters")
      (s/click! driver "[data-ship-new]")
      (s/wait-visible! driver ".assembly__save")
      (is (= "Working copy" (s/js driver "() => document.querySelector('.assembly__save input[name=name]').value")))
      (finally (s/quit! driver) (fixture/stop! started)))))
